harno_settings.admin_index:
  path: '/admin/config/veebiplatvorm'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Veebiplatvorm'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.settings_form:
  path: '/admin/config/veebiplatvorm/uldised-seaded'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoSettingsForm'
    _title: 'Veebiplatvormi üldised seaded'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.colors_form:
  path: '/admin/config/veebiplatvorm/kujundus'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoColorsForm'
    _title: 'Veebiplatvormi kujundus'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.frontpage_form:
  path: '/admin/config/veebiplatvorm/avaleht'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoFrontpageForm'
    _title: 'Veebiplatvormi avalehe bänneri ja taustapildi haldus'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.workers_import_form:
  path: '/admin/config/veebiplatvorm/tootajate-importimine'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoWorkersImportForm'
    _title: 'Töötajate andmete importimine failist'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
